OFFICE_PIS/urls.py
from django.conf.urls import url,include
from django.urls import  path
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

# views as auth_views
# app_name = 'office_pis'


urlpatterns =[

	path(r'staff/', views.StaffCreateView.as_view(), name ='staff-add'),
	path(r'staff/update/<pk>', views.StaffUpdateView.as_view(), name ='staff-update'), 
	path(r'darbandi/view', views.DarbandiListView.as_view(), name ='darbandi-view'), 

	path(r'staff', views.StaffListView.as_view(), name ='staff-list'),
	path(r'post/create', views.PostCreateView.as_view(), name ='post-add'),
	path(r'service/<pk>/create', views.ServiceCreateView.as_view(), name ='service-add'),
	path(r'leave/<pk>/create', views.LeaveCreateView.as_view(), name ='leave-add'),
	path(r'punishment/<pk>/create', views.PunishmentCreateView.as_view(), name ='punishment-add'),
	path(r'treatment/<pk>/create', views.TreatmentCreateView.as_view(), name ='treatment-add'),
	
	path(r'staff/<pk>', views.StaffDetailView.as_view(), name ='staff-detail'),
	path(r'darbandi/create', views.DarbandiCreateView.as_view(), name ='darbandi-add'),
	path(r'darbandi/update/<pk>', views.DarbandiUpdateView.as_view(), name ='darbandi-update'),

	path(r'staff/document/<pk>', views.pdfView, name ='staff-document-view'),
	path(r'staff/search/', views.SearchResultView.as_view(), name ='search-results'),


	# #user authentication
	
	path ('login/', auth_views.LoginView.as_view(),  name = 'login' ),
    path (r'pis', auth_views.LogoutView.as_view(), {'next_page' : '/'}, name = 'logout' ), 	
    path ('', TemplateView.as_view (template_name = 'home.html'), name ='home'),	
    

	# # yesma url matching garda staff ra delete rakheni hunxa narakhe ni hunxa
	# url(r'^del/(?P<pk>\d+)$', views.StaffDeleteView.as_view(), name ='staff-del'),
	
	
	# url(r'^staff/permanent$', views.permanentStaff, name ='staff-permanent'),
	# url(r'^staff/non-permanent$', views.non_permanentStaff, name ='staff-non-permanent'),
	

	
]

PIS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import  path


from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(r'pis/', include('OFFICE_PIS.urls')),
    
    
]
# +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# if settings.DEBUG:
    
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.conf.urls import url,include
from django.urls import  path
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

# views as auth_views
# app_name = 'office_pis'


urlpatterns =[

	path(r'staff/', views.StaffCreateView.as_view(), name ='staff-add'),
	path(r'staff/update/<pk>', views.StaffUpdateView.as_view(), name ='staff-update'), 
	path(r'darbandi/view', views.DarbandiListView.as_view(), name ='darbandi-view'), 

	path(r'staff', views.StaffListView.as_view(), name ='staff-list'),
	path(r'post/create', views.PostCreateView.as_view(), name ='post-add'),
	path(r'service/<pk>/create', views.ServiceCreateView.as_view(), name ='service-add'),
	path(r'leave/<pk>/create', views.LeaveCreateView.as_view(), name ='leave-add'),
	path(r'punishment/<pk>/create', views.PunishmentCreateView.as_view(), name ='punishment-add'),
	path(r'treatment/<pk>/create', views.TreatmentCreateView.as_view(), name ='treatment-add'),
	
	path(r'staff/<pk>', views.StaffDetailView.as_view(), name ='staff-detail'),
	path(r'darbandi/create', views.DarbandiCreateView.as_view(), name ='darbandi-add'),
	path(r'darbandi/update/<pk>', views.DarbandiUpdateView.as_view(), name ='darbandi-update'),

	path(r'staff/document/<pk>', views.pdfView, name ='staff-document-view'),
	path(r'staff/search/', views.SearchResultView.as_view(), name ='search-results'),


	# #user authentication
	
	path ('login/', auth_views.LoginView.as_view(),  name = 'login' ),
    path (r'pis', auth_views.LogoutView.as_view(), {'next_page' : '/'}, name = 'logout' ), 	
    path ('', TemplateView.as_view (template_name = 'home.html'), name ='home'),	
    

	
	
]

models.py
from __future__ import unicode_literals

from django.db import models
from django.core.files.storage import FileSystemStorage
from datetime import datetime 
from django.utils import timezone

per_nonper_choices= (
	('permanent','permanent'), 
	('non_permanent', 'non_permanent')
	)


# main PIS database is here....  """

class Office(models.Model):

	name = models.CharField(max_length=255)
	ph_num= models.CharField(max_length = 20)
	email= models.CharField(max_length = 255)

	def __str__(self):
		return self.name


class Post(models.Model):
	name = models.CharField(max_length=255)
	level = models.CharField(max_length=255)
	salary= models.IntegerField(default=0)

	def __str__(self):
		return self.name



class Staff(models.Model):

	name = models.CharField(max_length=255)
	photo=models.ImageField(blank=True, upload_to = 'pis/')
	ph_num= models.CharField(max_length = 20)
	dob = models.DateField(default= timezone.now)

	post = models.ForeignKey(Post, on_delete=models.SET_NULL, null = True, blank=True)
	office = models.ForeignKey(Office, on_delete=models.SET_NULL, null = True, blank=True)

	def __str__(self):
		return self.name





class Darbandi (models.Model):

	office = models.ForeignKey(Office, on_delete=models.CASCADE, null=True, blank=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null = True, blank=True)

	total_post = models.IntegerField(default=1)
	current_post = models.IntegerField(default=1)



	

class Address(models.Model):

	country = models.CharField(max_length=255)
	province = models.CharField(max_length=255)
	district = models.CharField(max_length=255)
	municipal = models.CharField(max_length=255)

	staff = models.OneToOneField(Staff, on_delete=models.CASCADE, null=True, blank=True)
	office = models.ForeignKey(Office, on_delete=models.CASCADE, null = True, blank=True)



	def __str__(self):
		return self.district


class Family(models.Model):

	mother_name = models.CharField(max_length = 255)
	father_name= models.CharField(max_length = 255)

	staff = models.OneToOneField(Staff, on_delete=models.CASCADE)

	def __str__(self):
		return self.father_name

class DesiredPerson (models.Model):

	name = models.CharField(max_length=255)
	relation= models.CharField(max_length=255)

	staff = models.OneToOneField(Staff, on_delete=models.CASCADE)

	def __str__(self):
		return self.name
 





class Appointment (models.Model):

	staff = models.OneToOneField(Staff, on_delete=models.CASCADE )
	office = models.ForeignKey(Office, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	appointment_date = models.DateField(default= timezone.now)


	
class Service (models.Model):

	
	start_date = models.DateField(default= timezone.now)
	end_date = models.DateField(default= timezone.now)
	appointment_type = models.CharField(max_length=255, default='new')

	staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.DO_NOTHING)
	office = models.ForeignKey(Office, on_delete=models.CASCADE)

	def __str__(self):
		return self.appointment_type



class EducationalInfo (models.Model):

	
	Degree = models.CharField(max_length=255)
	address = models.CharField(max_length=255)
	institue_name = models.CharField(max_length=255)

	staff = models.ForeignKey(Staff, on_delete=models.CASCADE)

	def __str__(self):
		return self.Degree





class LeaveInfo (models.Model):

	
	leave_type = models.CharField(max_length = 255)
	Leave_days = models.IntegerField(default = 0)
	staff = models.ForeignKey(Staff, on_delete = models.CASCADE)
	def __str__(self):
		return self.leave_type


class PunishmentInfo (models.Model):

	punishment_type = models.CharField(max_length=255)
	order_date = models.DateField(default= timezone.now)


	staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
	def __str__(self):
		return self.punishment_type



class Treatment (models.Model):

		amount = models.IntegerField (default=0)
		date = models.DateField (default=timezone.now)

		staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
		


class Document (models.Model):

	name = models.CharField(max_length=255)
	doc_file = models.FileField(upload_to = 'documents/', blank= True)

	staff = models.ForeignKey(Staff, on_delete=models.CASCADE)

	def __str__(self):
		return self.name
 

OFFICE_PIS/forms.py
from django import forms
from .models import Staff
# not needed
class Staff_form(forms.ModelForm):
	class meta:
		model=Blogpost
		fields= ['name','address', 'position', 'post']

OFFICE_PIS/templates/OFFICE_PIS/darbandi_form.html
{%  extends 'base.html'%} 

{% load crispy_forms_tags %}
{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
<div class="col-12">
  	<div class="card">
	  	<div class="card bg-info text-white">
		    <div class="card-header">दरबन्दी अपडेट </div>
		</div>
		<div class="card-body text-left">
			<div class="col-4">
                        
				<form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
				<!-- =============Django code for create form ======== -->
					<br>
										
											
						{% csrf_token %}
						{%  for field in form %}
						          {{field.label_tag}}<br>
						          <div class=" text-center">
						          {{ field}}<br>
						          </div>
						          
						          <br>
						{% endfor %}

					
			
				<!--=========== End of Djnao code to create form ========-->
			</div>
		</div>
		<div class="card-footer">					
			<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
			<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
		</div>
		</form>
	</div>
</div>
</div>

</form>
</center>

<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/darbandi_list.html
{%  extends 'base.html'%}

{% block content %}
{% load static %}







<!-- Darbandi List....  -->
<center>
<div class="container" > 
<div class="col-12">
<div class="card">
  	
	  	<div class="card bg-info text-white">
		    <div class="card-header">दरबन्दी विवरण </div>
		</div>
		<div class="card-body">

		<table class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>Post Id</th>
          <th>Post Name</th>
          <th>Total Posts</th>
          <th>Current Posts</th>

        </tr>
      </thead>
      <tbody>

      <!--============Djnago Code======-->
      {% for darbandi in darbandi_list %}
        <tr>
          <td>{{darbandi.id}}</td>
          <td> <a href = "{% url 'darbandi-update' darbandi.id %}"> {{darbandi.post}} </a></td>
          <td>{{darbandi.total_post}}</td>
          <td>{{darbandi.current_post}}</td>
    
          
        </tr>
       {% endfor %}
      </tbody>
    </table>


		<div class="card-footer">
			     <!-- Button of permanent and non permanent staff.. -->

              <a href = "{% url 'darbandi-add'  %}"><button type = 'submit' class="btn btn-secondary btn-sm "> दरबन्दी अपडेट </button></a>
              &nbsp;

              <a href = "{% url 'post-add'%}"><button type = 'submit' class="btn btn-secondary btn-sm "> पदहरु थप्नुहोस </button> </a>



		</div>
		</div>
	</div>
</div>
</div>





</center>

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/leaveinfo_form.html
 {%  extends 'base.html'%} 

{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
	<div class="col-12">
  		<div class="card">
	  		<div class="card bg-info text-white">
		    	<div class="card-header">बिदाको विवरण </div>
			</div>
			<div class="card-body">
				<form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
				<!-- =============Django code for create form ======== -->
					<br>
										
											
						
						{% csrf_token %}
						{{ form.as_p }}

					

				<!--=========== End of Djnago code to create form ========-->
		</div>
		<div class="card-footer">					
			<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
			<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
		</div>
		</form>
	</div>
</div>
</div>


</center>

<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/non_permanent.html
{%  extends 'base.html'%}

{% block content %}

<center>

<div class="container">
  <h2>Non Permanent Staff List</h2>
  
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Post</th>
          <th>Address</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>

      <!--============Djnago Code======-->
      {% for staff in staff_list %}
        <tr>
          <td><a href = "{% url 'staff-detail' staff.id %}"> {{staff.name}} </a></td>
          <td>{{staff.post}}</td>
          <td>{{staff.address}}</td>
          <td>{{staff.ph_num}}</td>
          
        </tr>
       {% endfor %}
      </tbody>
    </table>
  </div>
</div>




</center>


{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/permanent.html
{%  extends 'base.html'%}

{% block content %}
<!--============== Staff list========== -->


			
<center>

<div class="container">
  <h2>Permanent Staff List</h2>
  
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Post</th>
          <th>Address</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>

      <!--============Djnago Code======-->
      {% for staff in staff_list %}
        <tr>
          <td><a href = "{% url 'staff-detail' staff.id %}"> {{staff.name}} </a></td>
          <td>{{staff.post}}</td>
          <td>{{staff.address}}</td>
          <td>{{staff.ph_num}}</td>
          
        </tr>
       {% endfor %}
      </tbody>
    </table>
  </div>
</div>




</center>



{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/post_form.html
{%  extends 'base.html'%} 

{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
	<div class="col-12">
  		<div class="card">
	  		<div class="card bg-info text-white">
		    	<div class="card-header">पद फाराम </div>
			</div>
			<div class="card-body">

						

				                                
				                            <form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
												<!-- =============Django code for create form ======== -->
													<br>
																		
																			
														{% csrf_token %}
														{%  for field in form %}
														          <div>
														          {{field.label_tag}}
														          {{ field }} 
														          </div>
														          <br>
														{% endfor %}

													

												<!--=========== End of Djnago code to create form ========-->
				                              
				                          
				                    
				
			</div>
			<div class="card-footer">					
				<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
				<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
			</div>
		</form>
		</div>
	</div>
</div>


</center>

<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/punishmentinfo_form.html
 {%  extends 'base.html'%} 

{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
	<div class="col-12">
  		<div class="card">
	  		<div class="card bg-info text-white">
		    	<div class="card-header">सजायको विवरण </div>
			</div>
			<div class="card-body">
				<form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
				<!-- =============Django code for create form ======== -->
					<br>
										
											
						
						{% csrf_token %}
						{{ form.as_p }}

					

				<!--=========== End of Djnago code to create form ========-->
		</div>
		<div class="card-footer">					
			<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
			<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
		</div>
		</form>
	</div>
</div>
</div>


</center>

<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/service_form.html
 {%  extends 'base.html'%} 

{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
	<div class="col-12">
  		<div class="card">
	  		<div class="card bg-info text-white">
		    	<div class="card-header">सेवाको विवरण </div>
			</div>
			<div class="card-body">
				<form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
				<!-- =============Django code for create form ======== -->
					<br>
										
											
						{% csrf_token %}
						{{ form.as_p }}
					

				<!--=========== End of Djnago code to create form ========-->
		</div>
		<div class="card-footer">					
			<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
			<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
		</div>
		</form>
	</div>
</div>
</div>


</center>

<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/staff_confirm_delete.html
{%  extends 'base.html'%}

{% block content %}

<center>
<form action = '' method = 'POST'>

{% csrf_token %}	
Are you sure want to delete {{object.name}} ??
<input  type = 'submit' value = 'Confirm'>

</form>
</center>

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/staff_form.html
{%  extends 'base.html'%} 


{% load crispy_forms_tags %}
{% load static %}
					
{% block content %}

<center>
<div class="container" >
<div class="col-12">
  	<div class="card">
	  	<div class="card bg-info text-white">
		    <div class="card-header">व्याक्तिगत विवरण </div>
		</div>

<!-- ==============Main Form============-->


<!-- Form Start -->
<!-- Generating Start -->
        <div class="generating-area ">
            <div class="container">
                 
                <form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
					<!-- =============Django code for create form ======== -->
										
					{% csrf_token %}

					<div class="row">
								
									<!-- First Basic staff Form-->
									<div class="col-lg-6 col-md-6">
				                        <div class="single-generating d-flex mb-30">
				                            
				                            <div class="generating-cap text-left">
				                                
				                            	
				                                {%  for field in form %}

				                                {{ field|as_crispy_field }}&nbsp;<br>
				                                {% endfor %}
				                                
				                              
				                            </div>
				                        </div>
				                    </div> <br>

						{{ inlines.management_form|crispy }}
                   		{% for formset in inlines %}

                   			<!-- Address Form-->
							{% if forloop.counter == 1 %}
							
									<div class="col-lg-6 col-md-6">
				                        <div class="single-generating d-flex mb-30">
				                            
				                            <div class="generating-cap text-left">
				                                <h4>Address:</h4>
				                                <p>
				                                

				                                {{ formset|crispy }}
				                                 </p>
				                            </div>
				                        </div>
				                    </div> 

				            <!-- Family Form-->
				            {% elif forloop.counter == 2 %}
							
									<div class="col-lg-6 col-md-6">
				                        <div class="single-generating d-flex mb-30">
				                            
				                            <div class="generating-cap text-left">
				                                <h4>Family Info:</h4>
				                                <p>
				                                
				                                {{ formset|crispy }}
				                                 </p>
				                            </div>
				                        </div>
				                    </div> 


				            <!-- Desired Person Form-->
                    		{% elif forloop.counter == 3 %}
									<div class="col-lg-6 col-md-6">
				                        <div class="single-generating d-flex mb-30">
				                            
				                            <div class="generating-cap text-left">
				                                <h4>Desired Person:</h4>
				                                <p>
				                                {{ formset|crispy }}
				                                 </p>
				                            </div>
				                        </div>
				                    </div> <br>


				            <!-- Appointment  Form-->
				            {% elif forloop.counter == 4 %}
									<div class="col-lg-6 col-md-6">
				                        <div class="single-generating d-flex mb-30">
				                            
				                            <div class="generating-cap text-left">
				                                <h4>Appointment Info:</h4>
				                               
											    <table class="table table-bordered table-hover">
													<thead class="thead-light">
				                                <p>
				                               
									
				                               		<tr>
					                                    <th>Office </th>
					                                    <th> Post</th>
					                                    <th> Appointment Date</th>
					                           
					                                </tr>
					                                </thead>
					                                <tbody>
					                                	{% for fields in formset %}
					                                    <tr>
					                                        <td>{{ fields.office }}</td>
					                                        <td>{{ fields.post }}</td>
					                                        <td>{{ fields.appointment_date }}</td>
					                                            
					                                    </tr>
						                                {% endfor %}
						                            </tbody>
						                        </table>
				                                </p>

				                            </div>
				                        </div>
				                    </div> <br><br>

							
							<!-- Education Form-->		
                    		{% elif forloop.counter == 5 %}
                    			<div class="col-lg-12 col-md-12">
                        			<div class="single-generating d-flex mb-30">
                            
                            			<div class="generating-cap">
                            			<h4>Education:</h4>
                                			<div class="table-responsive">
											    <table class="table table-bordered table-hover">
													<thead class="thead-light">

											        <tr>
					                                    <th>Degree </th>
					                                    <th> Institute</th>
					                                    <th> Address</th>
					                                    
					                           
					                                </tr>
					                                </thead>
					                                <tbody>
					                                	{% for fields in formset %}
					                                    <tr>
					                                        <td>{{ fields.Degree }}</td>
					                                        <td>{{ fields.institue_name }}</td>
					                                        <td>{{ fields.address }}</td>
					                                            
					                                        </tr>
						                                {% endfor %}
						                            </tbody>
											    </table>						              
											</div>
                            			</div>
			                        </div>
			                    </div>


			                <!-- Documents Form-->
			                {% elif forloop.counter == 6 %}
                    			<div class="col-lg-12 col-md-12">
                        			<div class="single-generating d-flex mb-30">
                            
                            			<div class="generating-cap text-left">
                                			
											        <h4>Documents:</h4>
											        <div class="table-responsive">
											    		<table class="table table-bordered table-hover">
														<thead class="thead-light">


																<tr>
					                                              <th>Name </th>
					                                              <th> Document File</th>
					                                              
					                                            </tr>
					                                        </thead>
					                                        <tbody>
					                                       {% for fields in formset %}
					                                        <tr>
					                                            <td>{{ fields.name }}</td>
					                                            <td>{{ fields.doc_file }}</td>
					                                            
					                                        </tr>
						                                {% endfor %}
						                                 </table>
						                            </div>
											   						              
											</div>
                            			</div>
			                        </div>
			                    </div>
              				{% endif %}	
        				{% endfor %}     
            		</div>
					<div class="card-footer">					
						<button  type = "submit" class="btn btn-success" > पेश गर्नुहोस </button>&nbsp;
						<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>
</div>
<!--============End of main Form========= -->

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/staff_list.html
{%  extends 'base.html'%}

{% block content %}

{% load static %}


<center>





<!-- Search button HTML tags.. --> 
 <form style ="text-align:right" action = "{% url 'search-results' %}" method = "get">
	<input name ="q" type = "text" placeholder ="Search ...">
	<!-- yaha q variable name ho jun views ma use garinxa-->

	<button type = 'submit'> Go </button> 
</form>	



<!--============== Staff list========== -->


			
<center>

<div class="container">
  <h2>कर्मचारीहरु</h2>


  
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Post</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Father Name </th>
        </tr>
      </thead>
      <tbody>

      <!--============Djnago Code======-->
        {% for staff in staff_list %}
                   


        <tr>
            <td>{{ staff.id }}</td>
            <td><a href = "{% url 'staff-detail' staff.id %}">{{ staff.name }}</a></td>
            <td>{{ staff.post }}</td>
            <td>{{ staff.address }}</td>
            <td>{{ staff.ph_num }}</td>
            <td>{{ staff.family }}</td>
           

        </tr>
          {% endfor%}     
               

      </tbody>
    </table>

              
  </div>
</div>




<!-- Button of permanent and non permanent staff.. -->


<a href = "#"><button type = 'submit' class="btn btn-secondary"> Permanent Staff </button></a>

&nbsp;
<a href = "#"><button type = 'submit' class="btn btn-secondary"> Non Permanent Staff </button> </a>



</center>

{% endblock %}

OFFICE_PIS/templates/OFFICE_PIS/treatment_form.html
 {%  extends 'base.html'%} 

{% block content %}


<!-- ==============Main Form============-->
<center>
<div class="container" >
	<div class="col-12">
  		<div class="card">
	  		<div class="card bg-info text-white">
		    	<div class="card-header">उपचार खर्च विवरण </div>
			</div>
			<div class="card-body">
				<form action = '' method ='POST' enctype = 'multipart/form-data'> <!-- enctype le  media upload gareko -->
				
				
				<!-- =============Django code for create form ======== -->
					<br>
										
											
						{% csrf_token %}
						{{ form.as_p }}

					

				<!--=========== End of Djnago code to create form ========-->
		</div>
		<div class="card-footer">					
			<button  type = "submit" class="btn btn-success"> पेश गर्नुहोस </button>&nbsp;
			<button  type = "cancel" class="btn btn-warning"> रद्द गर्नुहोस </button>
		</div>
		</form>
	</div>
</div>
</div>


</center>

<!--============End of main Form========= -->

{% endblock %}